Transform: AWS::Serverless-2016-10-31
Description: Infrastructure for cloudwatch-log-group-enforcer
Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      RoleName: cloudwatch-log-group-enforcer
      Policies:
        - PolicyName: cloudwatch-log-group-enforcer-policy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - logs:DescribeLogGroups
                  - logs:PutRetentionPolicy
                  - sts:GetCallerIdentity
                  - organizations:ListAccounts
                Resource:
                  - "*"
              - Effect: Allow
                Action:
                  - sts:AssumeRole
                Resource:
                  - arn:aws:iam::008356366354:role/cloudwatch-log-group-enforcer-list-accounts
                  - arn:aws:iam::*:role/cloudwatch-log-group-enforcer-target-account-role
  Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../lambda_dist/
      Handler: cloudwatch_log_group_enforcer/main.handler
      Events:
        ScheduledTrigger:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)
      Runtime: python3.9
      FunctionName: cloudwatch-log-group-enforcer
      MemorySize: 128
      Role: !GetAtt Role.Arn
      Timeout: 300
  ErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      MetricName: Errors
      Namespace: AWS/Lambda
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      Period: 60
      TreatMissingData: notBreaching
      Statistic: Sum
      Threshold: 0
      ActionsEnabled: true
      AlarmActions:
        - !ImportValue notification-topic
      Dimensions:
        - Name: FunctionName
          Value: !Ref Function
