Description: IAM role for use by AlexChesters/cloudwatch-log-group-enforcer
Resources:
  LogGroupEnforcerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS:
                - arn:aws:iam::723247229166:role/cloudwatch-log-group-enforcer
              Service:
                - lambda.amazonaws.com
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS:
                - arn:aws:iam::723247229166:root
            Condition:
              StringEquals:
                aws:PrincipalOrgID: o-hru7a3vwm2
              ArnLike:
                aws:PrincipalARN: arn:aws:iam::723247229166:role/aws-reserved/sso.amazonaws.com/*
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      RoleName: cloudwatch-log-group-enforcer-list-accounts
      Policies:
        - PolicyName: cloudwatch-log-group-enforcer-policy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:ListStackInstances
                Resource:
                  - !Sub "arn:${AWS::Partition}:cloudformation:eu-west-1:${AWS::AccountId}:stackset/log-group-enforcer-role:*"
